navigate:
  name: Navigate a target device to a specific URL
  description: >
    This service allows you to navigate a target device to a specific URL.
  fields:
    target_device:
      description: The device to navigate.
      example: "remote_assist_display.living_room"
      required: true
      selector:
        device:
          filter:
            - integration: remote_assist_display
    url:
      description: The URL to navigate to.
      example: "https://www.home-assistant.io/"
      required: true
      selector:
          text: