name: Build

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build-alpine-arm64-application:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull builder image
      run: |
        docker buildx create --use
        docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Build application
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${PWD}:/usr/src/app \
          ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER dist/
        sudo chmod -R 755 dist/

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: remote-assist-display-app-alpine-arm64
        path: application/dist/remote-assist-display-app-alpine-arm64

  build-android:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
    - uses: actions/checkout@v4

    - name: Pull android builder image
      run: |
        docker pull ghcr.io/${{ github.repository }}/rad-builder-android:latest

    - name: Fix repository root permissions
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}

    - name: debugging
      run: |
        pwd
        ls -la
        ls -la build

    - name: Build APK
      run: |
        docker run --rm \
        -v ${{ github.workspace }}/application:/home/user/hostcwd \
        -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
        ghcr.io/${{ github.repository }}/rad-builder-android:latest \
        android debug

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER build/bin/
        sudo chmod -R 755 build/bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
          name: remote-assist-display-debug.apk
          path: application/build/bin/*.apk
