name: Build

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build-alpine-arm64-application:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: debug
      run: |
        pwd
        ls -la

    - name: Pull builder image
      run: |
        docker buildx create --use
        docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Build application
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${PWD}:/usr/src/app \
          ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: debug
      run: |
        ls -la

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: remote-assist-display-app-alpine-arm64
        path: ./dist/remote-assist-display-app-alpine-arm64

  build-android:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Prepare pywebview jar
      run: |
        mkdir -p libs
        pipenv run python -c "from webview import util; import shutil; shutil.copy(util.android_jar_path(), 'libs/pywebview-android.jar')"
    - name: Pull buildozer image
      run: |
        docker pull kivy/buildozer:latest
    - name: Build APK
      run: |
        docker run --rm \
        -v ${{ github.workspace }}://home/user/hostcwd \
        -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
        kivy/buildozer:latest \
        android debug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
          name: debug-apk
          path: bin/*.apk
