name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: read
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Get version
      id: version
      run: |
        VERSION=$(cat ../VERSION)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        # Remove v prefix from tag
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        if [ "$VERSION" != "$TAG_VERSION" ]; then
          echo "Error: VERSION file ($VERSION) does not match release tag ($TAG_VERSION)"
          exit 1
        fi

    - name: Update version in files
      run: |
        cd ..
        python3 scripts/update_version.py
        cd application

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull builder image
      run: |
        docker buildx create --use
        docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Build application
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${PWD}:/usr/src/app \
          ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER dist/
        sudo chmod -R 755 dist/

    - name: Rename and generate checksum for Alpine binary
      run: |
        cd dist
        mv remote-assist-display-app-alpine-arm64 remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64
        sha256sum remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64 > remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64.sha256

    - name: Pull android builder image
      run: |
        docker pull ghcr.io/${{ github.repository }}/rad-builder-android:latest

    - name: Fix repository root permissions
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}

    - name: Build APK
      run: |
        docker run --rm \
        -v ${{ github.workspace }}/application:/home/user/hostcwd \
        -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
        ghcr.io/${{ github.repository }}/rad-builder-android:latest \
        android debug

    - name: Fix APK permissions and rename
      run: |
        sudo chown -R $USER:$USER build/bin/
        sudo chmod -R 755 build/bin/
        cd build/bin
        mv *.apk remote-assist-display-${{ steps.version.outputs.version }}.apk

    - name: Generate APK checksum
      run: |
        cd build/bin
        sha256sum remote-assist-display-${{ steps.version.outputs.version }}.apk > remote-assist-display-${{ steps.version.outputs.version }}.apk.sha256

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          application/dist/remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64
          application/dist/remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64.sha256
          application/build/bin/remote-assist-display-${{ steps.version.outputs.version }}.apk
          application/build/bin/remote-assist-display-${{ steps.version.outputs.version }}.apk.sha256
