name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull builder image
      run: |
        docker buildx create --use
        docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Build application
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${PWD}:/usr/src/app \
          ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER dist/
        sudo chmod -R 755 dist/

    - name: Generate checksum
      run: |
        cd dist
        sha256sum remote-assist-display-app-alpine-arm64 > remote-assist-display-app-alpine-arm64.sha256

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          application/dist/remote-assist-display-app-alpine-arm64
          application/dist/remote-assist-display-app-alpine-arm64.sha256