name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: read
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Prepare for release
      run: |
        cd ..
        # Strip the -dev suffix if present
        python3 scripts/update_version.py release
        # Check what the stripped version is
        VERSION=$(cat VERSION)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        # Remove v prefix from tag
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        if [ "$VERSION" != "$TAG_VERSION" ]; then
          echo "Error: VERSION file ($VERSION) does not match release tag ($TAG_VERSION)"
          exit 1
        fi
      id: version

    - name: Update version in files
      run: |
        cd ..
        python3 scripts/update_version.py
        cd application

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull builder image
      run: |
        docker buildx create --use
        docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Build application
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${PWD}:/usr/src/app \
          ghcr.io/${{ github.repository }}/rad-builder-alpine-arm64:latest

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER dist/
        sudo chmod -R 755 dist/

    - name: Rename and generate checksum for Alpine binary
      run: |
        cd dist
        mv remote-assist-display-app-alpine-arm64 remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64
        sha256sum remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64 > remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64.sha256

    - name: Pull android builder image
      run: |
        docker pull ghcr.io/${{ github.repository }}/rad-builder-android:latest

    - name: Fix repository root permissions
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}

    - name: Set up debug keystore
      run: |
        mkdir -p ${{ github.workspace }}/.buildozer/android/platform/
        echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 -d > ${{ github.workspace }}/.buildozer/android/platform/debug.keystore
        chmod 600 ${{ github.workspace }}/.buildozer/android/platform/debug.keystore

    # For now we're still using debug builds, but this prepares for future release builds
    # Uncomment and configure these when ready for release builds:
    #- name: Set up release keystore
    #  if: github.event_name == 'release'
    #  run: |
    #    echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > ${{ github.workspace }}/.buildozer/android/platform/release.keystore
    #    chmod 600 ${{ github.workspace }}/.buildozer/android/platform/release.keystore
    #    # Update buildozer.spec with release keystore settings
    #    sed -i 's/android.keystore = .*/android.keystore = \/home\/user\/.buildozer\/android\/platform\/release.keystore/' build/buildozer.spec
    #    sed -i 's/android.keyalias = .*/android.keyalias = ${{ secrets.KEY_ALIAS }}/' build/buildozer.spec
    #    sed -i 's/android.keystore_password = .*/android.keystore_password = ${{ secrets.KEYSTORE_PASSWORD }}/' build/buildozer.spec
    #    sed -i 's/android.keyalias_password = .*/android.keyalias_password = ${{ secrets.KEY_PASSWORD }}/' build/buildozer.spec

    - name: Build APK
      run: |
        docker run --rm \
        -v ${{ github.workspace }}/application:/home/user/hostcwd \
        -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
        ghcr.io/${{ github.repository }}/rad-builder-android:latest \
        android debug

    - name: Fix APK permissions and rename
      run: |
        sudo chown -R $USER:$USER build/bin/
        sudo chmod -R 755 build/bin/
        cd build/bin
        mv *.apk remote-assist-display-${{ steps.version.outputs.version }}.apk

    - name: Generate APK checksum
      run: |
        cd build/bin
        sha256sum remote-assist-display-${{ steps.version.outputs.version }}.apk > remote-assist-display-${{ steps.version.outputs.version }}.apk.sha256

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          application/dist/remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64
          application/dist/remote-assist-display-${{ steps.version.outputs.version }}-alpine-arm64.sha256
          application/build/bin/remote-assist-display-${{ steps.version.outputs.version }}.apk
          application/build/bin/remote-assist-display-${{ steps.version.outputs.version }}.apk.sha256
  bump-version:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.repository.default_branch }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Bump to next development version
      run: |
        python scripts/update_version.py bump

    - name: Commit and push
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add VERSION custom_components/remote_assist_display/manifest.json application/build/buildozer.spec application/remote_assist_display/flask_config.py
        git commit -m "Bump version to next development version after release"
        git push