name: Update Android Builder Image

on:
  push:
    paths:
      - 'application/build/Dockerfile.build-android'
      - 'application/Pipfile'
      - 'application/Pipfile.lock'
      - '.github/workflows.update-android-builder.yaml'
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./application

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push builder image
      uses: docker/build-push-action@v5
      with:
        context: ./application
        platforms: linux/amd64
        push: true
        file: ./application/build/Dockerfile.build-android
        tags: |
          ghcr.io/${{ github.repository }}/rad-builder-android:latest
          ghcr.io/${{ github.repository }}/rad-builder-android:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/rad-builder-android:latest
        cache-to: type=inline